version: '3.4'

services:
  kassabnova:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

    ports:
      - "5000:5000"
  proxy:
    build:
        context:  ./nginx
        dockerfile: Dockerfile
    logging:
        driver: none #Comment this when you want nginx to show logs
    ports:
        - "80:80"
        - "443:443"
    volumes:
            - /etc/letsencrypt/:/etc/letsencrypt/
    links:
        - kassabnova