version: '3.4'

services:
  kassabnova:
    image: ${DOCKER_REGISTRY-}kassabnova
    build:
      context: .
      dockerfile: Dockerfile
  proxy:
    image: ${DOCKER_REGISTRY-}proxy
    build:
      context: .
      dockerfile: ./nginx/Dockerfile

